Repository FederatedAI/FATE-LLM, pull requests merged in 2023-09, with the labels that each got.

#21 Feature 1.3 doc bug fix
  doc/tutorial/fed_ipr/FedIPR-tutorial.ipynb
  doc/tutorial/parameter_efficient_llm/ChatGLM-6B_ds.ipynb
  doc/tutorial/parameter_efficient_llm/GPT2-example.ipynb
  python/fate_llm/model_zoo/ipr/alexnet.py
  python/fate_llm/model_zoo/ipr/distilbert.py
  python/fate_llm/model_zoo/ipr/gpt2.py
  python/fate_llm/model_zoo/ipr/resnet.py
  python/fate_llm/model_zoo/ipr/sign_block.py
  python/fate_llm/model_zoo/offsite_tuning/llama_ot.py
  python/fate_llm/trainer/fedipr_trainer.py
Labels: bug, enhancement

#22 Feature 1.3 doc bug fix
  doc/tutorial/fed_ipr/FedIPR-tutorial.ipynb
  doc/tutorial/offsite_tuning/Offsite_tuning_tutorial_0.ipynb
  python/fate_llm/dataset/qa_dataset.py
  python/fate_llm/model_zoo/offsite_tuning/gpt2_ot.py
Labels: bug

#23 Update & Remove redundent codes
  python/fate_llm/dataset/qa_dataset.py
  python/fate_llm/model_zoo/offsite_tuning/gpt2_ot.py
Labels: bug, enhancement

#25 remove constraint
  python/fate_llm/dataset/qa_dataset.py
Labels: bug

#26 Add file head
  python/fate_llm/dataset/qa_dataset.py
  python/fate_llm/model_zoo/ipr/alexnet.py
  python/fate_llm/model_zoo/ipr/distilbert.py
  python/fate_llm/model_zoo/ipr/gpt2.py
  python/fate_llm/model_zoo/ipr/resnet.py
  python/fate_llm/model_zoo/ipr/sign_block.py
  python/fate_llm/model_zoo/offsite_tuning/bloom_ot.py
  python/fate_llm/model_zoo/offsite_tuning/gpt2_ot.py
  python/fate_llm/model_zoo/offsite_tuning/llama_ot.py
  python/fate_llm/model_zoo/offsite_tuning/offsite_tuning_model.py
  python/fate_llm/trainer/fedipr_trainer.py
  python/fate_llm/trainer/offsite_tuning_trainer.py
Labels: documentation, enhancement

#27 Add offsite-tuning tutorial
  doc/tutorial/offsite_tuning/Offsite_tuning_tutorial.ipynb
  doc/tutorial/offsite_tuning/Offsite_tuning_tutorial_0.ipynb
Labels: documentation

#28 pellm update: support chatglm2, bloom
  python/fate_llm/dataset/glm_tokenizer.py
  python/fate_llm/dataset/prompt_tokenizer.py
  python/fate_llm/model_zoo/pellm/bloom.py
Labels: enhancement

#29 update doc: release note and builtin models
  README.md
  RELEASE.md
  doc/tutorial/builtin_models.md
Labels: documentation

#30 update release
  RELEASE.md
Labels: documentation

#31 fix parameter bug
  python/fate_llm/trainer/offsite_tuning_trainer.py
Labels: bug

#33 update version of doc
  RELEASE.md
Labels: documentation

#34 Develop 1.3
  doc/images/ot1.png
  doc/images/ot2.png
  doc/tutorial/offsite_tuning/README.md
Labels: documentation
