Repository FederatedAI/FATE-LLM, pull requests merged in 2024-06, with the labels that each got.

#83 add fedmkt
  python/fate_llm/algo/fedmkt/__init__.py
  python/fate_llm/algo/fedmkt/fedmkt.py
  python/fate_llm/algo/fedmkt/fedmkt_data_collator.py
  python/fate_llm/algo/fedmkt/fedmkt_trainer.py
  python/fate_llm/algo/fedmkt/token_alignment/__init__.py
  python/fate_llm/algo/fedmkt/token_alignment/spectal_token_mapping.py
  python/fate_llm/algo/fedmkt/token_alignment/token_align.py
  python/fate_llm/algo/fedmkt/token_alignment/vocab_mapping.py
  python/fate_llm/algo/fedmkt/utils/__init__.py
  python/fate_llm/algo/fedmkt/utils/dataset_sync_util.py
  python/fate_llm/algo/fedmkt/utils/generate_logit_utils.py
  python/fate_llm/algo/fedmkt/utils/tokenizer_tool.py
  python/fate_llm/algo/fedmkt/utils/vars_define.py
  python/fate_llm/dataset/qa_dataset.py
  python/fate_llm/model_zoo/pellm/gpt2.py
  python/fate_llm/model_zoo/pellm/opt.py
  python/fate_llm/model_zoo/pellm/parameter_efficient_llm.py
  python/fate_llm/runner/fedmkt_runner.py
  python/fate_llm/trainer/seq2seq_trainer.py
Labels: enhancement

#87 update fedmkt
  doc/tutorial/fedmkt/README.md
  doc/tutorial/fedmkt/fedmkt.ipynb
  doc/tutorial/parameter_efficient_llm/ChatGLM3-6B_ds.ipynb
  python/fate_llm/algo/fedmkt/fedmkt.py
  python/fate_llm/algo/fedmkt/fedmkt_data_collator.py
  python/fate_llm/algo/fedmkt/fedmkt_trainer.py
  python/fate_llm/algo/fedmkt/token_alignment/token_align.py
  python/fate_llm/algo/fedmkt/token_alignment/vocab_mapping.py
  python/fate_llm/algo/fedmkt/utils/generate_logit_utils.py
  python/fate_llm/algo/fedmkt/utils/vars_define.py
  python/fate_llm/runner/fedmkt_runner.py
Labels: documentation, enhancement

#81 Feature 2.1 evaluator
  README.md
  doc/fate_llm_evaluation.md
  examples/pellm/__init__.py
  examples/pellm/bloom_lora_config.yaml
  examples/pellm/test_bloom_lora.py
  examples/pellm/test_pellm_llmsuite.yaml
  python/fate_llm/evaluate/__init__.py
  python/fate_llm/evaluate/scripts/__init__.py
  python/fate_llm/evaluate/scripts/_options.py
  python/fate_llm/evaluate/scripts/config_cli.py
  python/fate_llm/evaluate/scripts/data_cli.py
  python/fate_llm/evaluate/scripts/eval_cli.py
  python/fate_llm/evaluate/scripts/fate_llm_cli.py
  python/fate_llm/evaluate/tasks/__init__.py
  python/fate_llm/evaluate/tasks/advertise_gen/advertise_utils.py
  python/fate_llm/evaluate/tasks/advertise_gen/default_advertise_gen.yaml
  python/fate_llm/evaluate/tasks/dolly_15k/default_dolly_15k.yaml
  python/fate_llm/evaluate/tasks/dolly_15k/dolly_utils.py
  python/fate_llm/evaluate/utils/__init__.py
  python/fate_llm/evaluate/utils/_io.py
  python/fate_llm/evaluate/utils/_parser.py
  python/fate_llm/evaluate/utils/config.py
  python/fate_llm/evaluate/utils/data_tools.py
  python/fate_llm/evaluate/utils/llm_evaluator.py
  python/fate_llm/evaluate/utils/model_tools.py
  python/setup.py
Labels: enhancement

#93 Feature 2.1.0 doc update
  examples/pellm/test_pellm_llmsuite.yaml
  python/fate_llm/evaluate/tasks/advertise_gen/default_advertise_gen.yaml
Labels: documentation

#95 update doc & release note
  README.md
  RELEASE.md
  doc/fate_llm_evaluate.md
Labels: documentation

#97 Fix document
  doc/tutorial/inferdpt/inferdpt_tutorial.ipynb
Labels: documentation
