Repository FederatedAI/FATE-LLM, pull requests merged in 2024-02, with the labels that each got.

#44 Feature 2.0.0 pellm
  python/fate_llm/dataset/data_collator/__init__.py
  python/fate_llm/dataset/glm_tokenizer.py
  python/fate_llm/dataset/prompt_dataset.py
  python/fate_llm/dataset/qa_dataset.py
  python/fate_llm/dataset/seq_cls_dataset.py
  python/fate_llm/dataset/tokenizers/__init__.py
  python/fate_llm/dataset/watermark.py
  python/fate_llm/model_zoo/pellm/bloom.py
  python/fate_llm/model_zoo/pellm/chatglm.py
  python/fate_llm/model_zoo/pellm/gpt2.py
  python/fate_llm/model_zoo/pellm/llama.py
  python/fate_llm/model_zoo/pellm/parameter_efficient_llm.py
  python/fate_llm/runner/__init__.py
  python/fate_llm/runner/homo_seq2seq_runner.py
  python/fate_llm/trainer/__init__.py
  python/fate_llm/trainer/fedipr_trainer.py
  python/fate_llm/trainer/offsite_tuning_trainer.py
  python/fate_llm/trainer/seq2seq_trainer.py
Labels: enhancement

#49 Feature 2.0.0 pellm
  python/fate_llm/model_zoo/pellm/chatglm.py
  python/fate_llm/model_zoo/pellm/llama.py
  python/fate_llm/model_zoo/pellm/parameter_efficient_llm.py
  python/fate_llm/model_zoo/pellm/qwen.py
Labels: bug, enhancement

#54 Feature 2.0.0 pellm
  python/fate_llm/model_zoo/pellm/parameter_efficient_llm.py
  python/fate_llm/trainer/seq2seq_trainer.py
Labels: enhancement

#56 update requirements
  python/requirements.txt
Labels: documentation

#57 Fix multi-GPU bugs Signed-off-by: weijingchen <talkingwallace@sohu.com>
  python/fate_llm/homo/fedavg.py
  python/fate_llm/homo/offsite_tuning.py
Labels: bug
